services:
  app:
    image: ghcr.io/dimibeziau/backend_wizia/app:latest
    container_name: wizia-app
    restart: unless-stopped
    volumes:
      - wizia-storage:/var/www/storage
      - wizia-public:/var/www/public_mounted
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      # Database
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # App
      APP_URL: ${APP_URL}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}

      # Mail
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}

      # Others
      KEY_API_GEMINI: ${KEY_API_GEMINI}
    depends_on:
      - db

  web:
    image: ghcr.io/dimibeziau/backend_wizia/nginx:latest
    container_name: wizia-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - wizia-public:/var/www/public
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: wizia-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wizia_db_prod
      MYSQL_ROOT_PASSWORD: wizia_password_prod
      MYSQL_PASSWORD: wizia_password_prod
      MYSQL_USER: wizia_user_prod
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wizia-pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  wizia-storage:
  wizia-public:
